services:
    _defaults:
        autoconfigure: true

    digitale_dinge_grid_ratio_widget.listener.backend_assets:
        class: DigitaleDinge\GridRatioWidgetBundle\EventListener\BackendAssetsListener
        arguments:
            - '@contao.routing.scope_matcher'
            - '@assets.packages'

    digitale_dinge_grid_ratio_widget.twig.extension:
        class: DigitaleDinge\GridRatioWidgetBundle\Twig\GridRatioExtension

    digitale_dinge_grid_ratio_widget.twig.runtime:
        class: DigitaleDinge\GridRatioWidgetBundle\Twig\GridRatioRuntime
