services:
    _defaults:
        autowire: true
        autoconfigure: true

    DigitaleDinge\GridRatioWidgetBundle\:
        resource: '../src/'
        exclude: '../src/{DigitaleDingeGridRatioWidgetBundle.php,ContaoManager,Widget}'
